"""description_required_image_type_auto

Revision ID: 38b0ae59ec3c
Revises: 4e03046ba3f4
Create Date: 2026-08-11 15:35:54.489308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b0ae59ec3c'
down_revision: Union[str, Sequence[str], None] = '4e03046ba3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_assets', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_assets', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
