"""SQLAlchemy ORM model for SVG icon assets."""

import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Integer,
    String,
    Text,
    JSON,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


# ── Enums ──────────────────────────────────────────────────────────────────────
class IconCategory(str, enum.Enum):
    ui = "ui"
    social = "social"
    communication = "communication"
    media = "media"
    navigation = "navigation"
    finance = "finance"
    nature = "nature"
    technology = "technology"
    travel = "travel"
    health = "health"
    food = "food"
    weather = "weather"
    security = "security"
    education = "education"
    business = "business"
    other = "other"


class IconStyle(str, enum.Enum):
    outline = "outline"
    filled = "filled"
    duotone = "duotone"
    flat = "flat"
    other = "other"


# ── ORM Model ──────────────────────────────────────────────────────────────────
class SvgIcon(Base):
    """Persists an icon asset (SVG or raster) with LLM-enriched metadata and R2 storage reference."""

    __tablename__ = "svg_icons"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )

    # ── Identity ────────────────────────────────────────────────────────────────
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    """Human-readable name, e.g. 'Account Alert'"""

    slug: Mapped[str] = mapped_column(String(255), nullable=False, unique=True, index=True)
    """URL-safe slug derived from filename, e.g. 'account-alert'"""

    original_filename: Mapped[str] = mapped_column(String(512), nullable=False)
    """Original file name on disk, e.g. 'account-alert.svg'"""

    file_format: Mapped[str] = mapped_column(String(20), nullable=False, default="svg")
    """File format: svg | png | jpg | webp | ico | gif"""

    # ── LLM-generated payload ───────────────────────────────────────────────────
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    """LLM-generated semantic description for embedding / search."""

    category: Mapped[IconCategory] = mapped_column(
        Enum(IconCategory, name="iconcategory"),
        nullable=False,
        default=IconCategory.other,
    )
    """Primary category classified by LLM."""

    style: Mapped[IconStyle] = mapped_column(
        Enum(IconStyle, name="iconstyle"),
        nullable=False,
        default=IconStyle.other,
    )
    """Visual style classified by LLM (outline, filled, etc.)."""

    tags: Mapped[list | None] = mapped_column(JSON, nullable=True)
    """List of keyword tags generated by LLM, e.g. ['user', 'profile', 'person']."""

    use_cases: Mapped[list | None] = mapped_column(JSON, nullable=True)
    """List of use-case strings, e.g. ['navigation', 'sidebar', 'user profile']."""

    keywords: Mapped[list | None] = mapped_column(JSON, nullable=True)
    """Alternative search terms / synonyms for the icon."""

    llm_raw: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    """Full raw JSON payload returned by the LLM (for debugging / re-processing)."""

    # ── SVG content ─────────────────────────────────────────────────────────────
    svg_content: Mapped[str | None] = mapped_column(Text, nullable=True)
    """Raw SVG markup — populated for SVG icons, NULL for raster formats."""

    # ── R2 Storage ──────────────────────────────────────────────────────────────
    r2_key: Mapped[str] = mapped_column(String(512), nullable=False, unique=True)
    """Object key inside the R2 bucket."""

    public_url: Mapped[str] = mapped_column(String(1024), nullable=False)
    """Publicly accessible CDN URL."""

    # ── File metadata ────────────────────────────────────────────────────────────
    file_size_bytes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    viewbox: Mapped[str | None] = mapped_column(String(100), nullable=True)
    """e.g. '0 0 24 24'"""

    # ── Pipeline state ───────────────────────────────────────────────────────────
    vectorized: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    """True once the embedding has been upserted into Qdrant."""

    vectorized_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Timestamps ───────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    def __repr__(self) -> str:
        return f"<SvgIcon id={self.id!r} slug={self.slug!r}>"
